services: 
  db: 
    image: postgres 
    ports:
      - "3536:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data 
    environment: 
      - POSTGRES_DB=development 
      - POSTGRES_USER=cursors 
      - POSTGRES_PASSWORD=root 

volumes: 
  pgdata: 